name: Build python with signature

on:
    [push, workflow_dispatch]
  
permissions:
    id-token: write
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Create Signature for Package
              uses: ./.github/actions/create-signature
              with:
                  package-name: "evidence-package"
                  package-repo-name: "evidence-package"
                  
            - name: Build
              run: |
                  python setup.py sdist bdist_wheel
